# Setup
title: 
description: A simple, beautiful, and powerful Jekyll theme for blogs
url: https://woo-seok-sung.github.io
avatar: ./_image/profile.png
paginate: 5
permalink: pretty
cover_image: ./_image/background.jpg

include:
  - _image

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: vszhub
  card: summary
logo: logo.png
social:
  name: Wooseok Sung
  links:
    - https://twitter.com/vszhub
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
# disqus: xxxxxx

# Specify the author for blog posts
author:
  name: Wooseok Sung
  url: https://github.com/Woo-Seok-Sung/
  email: skatefruit1226@gmail.com
